# TCL File Generated by Component Editor 15.0
# Mon Jun 08 20:03:17 BST 2015
# DO NOT MODIFY


# 
# bytes2words "bytes2words" v1.0
#  2015.06.08.20:03:17
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module bytes2words
# 
set_module_property DESCRIPTION ""
set_module_property NAME bytes2words
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME bytes2words
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL placebo
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file placebo.v VERILOG PATH placebo.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_streaming_sink_0
# 
add_interface avalon_streaming_sink_0 avalon_streaming end
set_interface_property avalon_streaming_sink_0 associatedClock clock_sink
set_interface_property avalon_streaming_sink_0 associatedReset reset_sink
set_interface_property avalon_streaming_sink_0 dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_0 symbolsPerBeat 8
set_interface_property avalon_streaming_sink_0 errorDescriptor ""
set_interface_property avalon_streaming_sink_0 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_0 maxChannel 0
set_interface_property avalon_streaming_sink_0 readyLatency 0
set_interface_property avalon_streaming_sink_0 ENABLED true
set_interface_property avalon_streaming_sink_0 EXPORT_OF ""
set_interface_property avalon_streaming_sink_0 PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink_0 asi_data data Input 64
add_interface_port avalon_streaming_sink_0 asi_valid valid Input 1
add_interface_port avalon_streaming_sink_0 asi_ready ready Output 1
add_interface_port avalon_streaming_sink_0 asi_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink_0 asi_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink_0 asi_error error Input 1


# 
# connection point avalon_streaming_source_0
# 
add_interface avalon_streaming_source_0 avalon_streaming start
set_interface_property avalon_streaming_source_0 associatedClock clock_sink
set_interface_property avalon_streaming_source_0 associatedReset reset_sink
set_interface_property avalon_streaming_source_0 dataBitsPerSymbol 64
set_interface_property avalon_streaming_source_0 errorDescriptor ""
set_interface_property avalon_streaming_source_0 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_0 maxChannel 0
set_interface_property avalon_streaming_source_0 readyLatency 0
set_interface_property avalon_streaming_source_0 ENABLED true
set_interface_property avalon_streaming_source_0 EXPORT_OF ""
set_interface_property avalon_streaming_source_0 PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_0 aso_data data Output 64
add_interface_port avalon_streaming_source_0 aso_valid valid Output 1
add_interface_port avalon_streaming_source_0 aso_ready ready Input 1
add_interface_port avalon_streaming_source_0 aso_startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source_0 aso_endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source_0 aso_error error Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink clock_rst_n reset_n Input 1

