# TCL File Generated by Component Editor 15.0
# Mon Jun 08 19:46:40 BST 2015
# DO NOT MODIFY


# 
# words2bytes "words2bytes" v1.0
#  2015.06.08.19:46:40
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module words2bytes
# 
set_module_property DESCRIPTION ""
set_module_property NAME words2bytes
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME words2bytes
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL placebo
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file placebo.v VERILOG PATH placebo.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_streaming_sink_0
# 
add_interface avalon_streaming_sink_0 avalon_streaming end
set_interface_property avalon_streaming_sink_0 associatedClock clock_clock
set_interface_property avalon_streaming_sink_0 associatedReset reset
set_interface_property avalon_streaming_sink_0 dataBitsPerSymbol 64
set_interface_property avalon_streaming_sink_0 errorDescriptor ""
set_interface_property avalon_streaming_sink_0 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_0 maxChannel 0
set_interface_property avalon_streaming_sink_0 readyLatency 0
set_interface_property avalon_streaming_sink_0 ENABLED true
set_interface_property avalon_streaming_sink_0 EXPORT_OF ""
set_interface_property avalon_streaming_sink_0 PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink_0 asi_data data Input 64
add_interface_port avalon_streaming_sink_0 asi_valid valid Input 1
add_interface_port avalon_streaming_sink_0 asi_ready ready Output 1
add_interface_port avalon_streaming_sink_0 asi_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink_0 asi_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink_0 asi_error error Input 1


# 
# connection point avalon_streaming_source_0
# 
add_interface avalon_streaming_source_0 avalon_streaming start
set_interface_property avalon_streaming_source_0 associatedClock clock_clock
set_interface_property avalon_streaming_source_0 associatedReset reset
set_interface_property avalon_streaming_source_0 dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_0 errorDescriptor ""
set_interface_property avalon_streaming_source_0 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_0 maxChannel 0
set_interface_property avalon_streaming_source_0 readyLatency 0
set_interface_property avalon_streaming_source_0 symbolsPerBeat 8
set_interface_property avalon_streaming_source_0 ENABLED true
set_interface_property avalon_streaming_source_0 EXPORT_OF ""
set_interface_property avalon_streaming_source_0 PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_0 aso_data data Output 64
add_interface_port avalon_streaming_source_0 aso_valid valid Output 1
add_interface_port avalon_streaming_source_0 aso_ready ready Input 1
add_interface_port avalon_streaming_source_0 aso_startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source_0 aso_endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source_0 aso_error error Output 1


# 
# connection point clock_clock
# 
add_interface clock_clock clock end
set_interface_property clock_clock clockRate 0
set_interface_property clock_clock ENABLED true
set_interface_property clock_clock EXPORT_OF ""
set_interface_property clock_clock PORT_NAME_MAP ""
set_interface_property clock_clock CMSIS_SVD_VARIABLES ""
set_interface_property clock_clock SVD_ADDRESS_GROUP ""

add_interface_port clock_clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset clock_rst_n reset_n Input 1

